# Generated by Django 2.2.5 on 2021-08-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210712_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'Email'), ('kakao', 'Kakao'), ('github', 'Github')], default='email', max_length=50),
        ),
    ]
